name: Build and deploy an app to AKS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  # Local environment variables used later in the workflow
  AZURE_CONTAINER_REGISTRY: 'acseshop121'
  PRODUCT_CONTAINER_NAME: 'productservice'
  STORE_CONTAINER_NAME: 'storeimage'
  RESOURCE_GROUP: 'rg-eshop'
  CLUSTER_NAME: 'aks-eshop'
  PRODUCT_DEPLOYMENT_MANIFEST_PATH: './backend-deploy.yml'
  STORE_DEPLOYMENT_MANIFEST_PATH: './frontend-deploy.yml'
  PRODUCT_DOCKER_PATH: './Products/Dockerfile'
  STORE_DOCKER_PATH: './Store/Dockerfile'

jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      # Logs in with your Azure credentials stored in GitHub secrets
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      # Builds and pushes an image up to your Azure Container Registry
      - name: Build and push backend image to ACR
        working-directory: 'dotnet-kubernetes'
        run: |
              az acr build --file ${{ env.PRODUCT_DOCKER_PATH }} \
                 --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.PRODUCT_CONTAINER_NAME }}:${{ github.sha }} \
                 --registry ${{ env.AZURE_CONTAINER_REGISTRY }} \
                 --resource-group ${{ env.RESOURCE_GROUP }} .

      - name: Build and push frontend image to ACR
        working-directory: 'dotnet-kubernetes'
        run: |
              az acr build --file ${{ env.STORE_DOCKER_PATH }} \
                 --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.STORE_CONTAINER_NAME }}:${{ github.sha }} \
                 --registry ${{ env.AZURE_CONTAINER_REGISTRY }} \
                 --resource-group ${{ env.RESOURCE_GROUP }} .
                 
